module.exports = [
  { company: '10,000ft',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: '2 Handed Coding',
    state: 'unknown',
    city: 'unknown',
    size: '<10',
    hires: [ 'Mobile Application Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: '4Life Research USA, LLC',
    state: 'UT',
    city: 'Sandy',
    size: '1,000-10,000',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: '8ninths',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: '99Gamers',
    state: 'CA',
    city: 'San Francisco',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Accretive Technology Group',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'ACTIVE Network',
    state: 'WA',
    city: 'Bothell',
    size: '1,000-10,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Affinity Gaming',
    state: 'NV',
    city: 'Las Vegas',
    size: '1,000-10,000',
    hires: [ 'Digital Marketing Analyst' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Alien Code LLC',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Amadeus Revenue Integrity',
    state: 'AZ',
    city: 'Tuscon',
    size: '10-100',
    hires: [ 'Product Specialist' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Amazon',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires:
     [ 'Web Development Engineer',
       'UX Prototyper/Design Technologist',
       'Front-End Developer',
       'QA Engineer',
       'Creative Services Contractor',
       'Systems Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 3,
    python: 0,
    ux: 2,
    rails: 2 },
  { company: 'Analytics Pros',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires:
     [ 'Software Developer',
       'Mobile Analytics Developer',
       'Software Developer in Analytics Integration' ],
    ios: 1,
    ruby: 0,
    javascript: 2,
    python: 0,
    ux: 0 },
  { company: 'Anonyome Labs',
    state: 'CA',
    city: 'San Francisco',
    size: '10-100',
    hires: [ 'iOS Developer Contract-to-Hire' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'AnswerDash',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Web Application Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Apex Learning',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Project Manager' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'AppSheet',
    state: 'WA',
    city: 'Bellevue',
    size: '<10',
    hires: [ 'Front-end Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Apptentive',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Associate Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'ArrowPointe Federal Credit Union',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Application Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Atelier Ace',
    state: 'OR',
    city: 'Portland',
    size: '100-1,000',
    hires: [],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Atomic Infotech',
    state: 'WA',
    city: 'Bellevue',
    size: '<10',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Attain',
    state: 'unknown',
    city: 'unknown',
    size: '<10',
    hires: [ 'Senior Analyst' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Bargreen Ellingson',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Lead Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Belief Agency',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Main Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Belkin',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Big Fish Games',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Development Engineer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'BitTitan',
    state: 'WA',
    city: 'Kirkland',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Blackjack Apprenticeship',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Blink UX',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'blinkx',
    state: 'WA',
    city: 'San Francisco',
    size: '100-1,000',
    hires: [ 'Junior Javascript Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Blue Raster',
    state: 'VA',
    city: 'Arlington',
    size: '10-100',
    hires: [ 'GIS' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Blueprint Consulting Services, LLC',
    state: 'WA',
    city: 'Bellevue',
    size: '10-100',
    hires: [ 'Technical Recruiter' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Brand Candy Media Group',
    state: 'NY',
    city: 'New York',
    size: '<10',
    hires: [ 'Unicorn' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'buildpulse',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'JavaScript Developer', 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 1,
    ux: 0 },
  { company: 'Capital One Financial Corporation',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires: [ 'Front-End Developer', 'Front-End Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 1 },
  { company: 'CDK Global',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Celedon Partners',
    state: 'WA',
    city: 'Bothell',
    size: '10-100',
    hires: [ 'Junior Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Cequint',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Test Engineer II', 'Software Engineer (in Test)' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 2,
    ux: 0 },
  { company: 'Ciena Corporation',
    state: 'unknown',
    city: 'unknown',
    size: '1,000-10,000',
    hires: [ 'IT Associate, Applications' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Clearhead: The Digital Optimization Agency',
    state: 'TX',
    city: 'Austin',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'ClikFocus',
    state: 'CO',
    city: 'Colorado Springs',
    size: '<10',
    hires: [ 'Junior Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Clutch',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Development Engineer', 'Software Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Coalfire',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Comr.se',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'CoolBlueWeb',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Coolr',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Cozi',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Creately Design',
    state: 'WA',
    city: 'Lynwood',
    size: '<10',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'CX Technology',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'DatStat',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Technical Specialist (Front-End Web Developer)' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Dawley & Associates',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'DC Health Benefit Exchange Authority',
    state: 'Wasington D.C',
    city: 'Washington D.C.',
    size: '10-100',
    hires: [ 'Junior Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Decielo Consulting',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Consulting Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Deloitte Digital',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Associate Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Design Commission',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'DevHub',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Dial App, Inc.',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'CTO' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Dish Network',
    state: 'CO',
    city: 'Englewood',
    size: '10,000+',
    hires: [],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Dolly',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Eddie Bauer',
    state: 'WA',
    city: 'Bellevue',
    size: '1,000-10,000',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'eigital',
    state: 'CA',
    city: 'Los Angeles',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Elastic',
    state: 'CA',
    city: 'Mountain View',
    size: '10-100',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'En Masse Entertainment',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Associate Product Manager' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Eventemo',
    state: 'United Kingdom',
    city: 'London',
    size: '10-100',
    hires: [ 'JavaScript Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'EVIDENCE.com',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Junior Front-End Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Expedia, Inc.',
    state: 'WA',
    city: 'Bellevue',
    size: '10,000+',
    hires:
     [ 'Associate Software Developer',
       'Software Developer',
       'Associate Software Development Engineer',
       'Assoc. Software Dev. Eng.',
       'Software Dev Engineer I',
       'Associate Software Developer',
       'Senior Visual Designer',
       'Assoc. Software Dev. Eng.',
       'Associate Technical Project Manager',
       'Front-End Developer',
       'Associate Software Engineer',
       'Associate Software Engineer',
       'Associate Software Development Engineer',
       'Software Developer',
       'Associate Software Development Engineer',
       'Software Developer',
       'Software Development Engineer I (SDE I)',
       'Software Developer',
       'Software Developer',
       'Software Developer',
       'Associate Software Development Engineer',
       'Web Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 11,
    python: 1,
    ux: 2,
    rails: 7 },
  { company: 'ExtraHop Networks',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Support Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'F2M2',
    state: 'TX',
    city: 'San Antonio',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'F5 Networks',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Software Engineer I', 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 1,
    ux: 0 },
  { company: 'Facebook',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'UI Specialist' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Faithlife',
    state: 'WA',
    city: 'Bellingham',
    size: '100-1,000',
    hires: [ 'Web Coder' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Felt',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'IOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Fidelity Investments',
    state: 'MA',
    city: 'Boston',
    size: '10,000+',
    hires: [ 'Full-Stack Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Financial Recovery Technologies',
    state: 'MA',
    city: 'Medford',
    size: '10-100',
    hires: [ 'Consultant' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'FINE',
    state: 'OR',
    city: 'Portland',
    size: '10-100',
    hires: [ 'Junior Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Fitbit',
    state: 'CA',
    city: 'San Francisco',
    size: '100-1,000',
    hires: [ 'Tier II Technical Support' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Five Talent, Inc.',
    state: 'OR',
    city: 'Bend',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'FizzMint',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Python Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'FlexMinder',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Flowroute',
    state: 'CA',
    city: 'Oceanside',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'ForgeRock',
    state: 'unknown',
    city: 'unknown',
    size: '100-1,000',
    hires: [ 'UI Intern' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Formidable Labs',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires:
     [ 'Software Engineer',
       'Software Engineer',
       'Software Engineer',
       'Software Engineer',
       'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 5,
    python: 0,
    ux: 0 },
  { company: 'Fred Hutchinson Cancer Research Center',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'R Programmer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Fresh Consulting',
    state: 'WA',
    city: 'Bellevue',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Full Circle',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Fuze, Inc.',
    state: 'CA',
    city: 'San Francisco',
    size: '100-1,000',
    hires: [ 'Product Manager' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Gatheredtable',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'UX Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Geezeo, Inc.',
    state: 'CT',
    city: 'Tolland',
    size: '10-100',
    hires: [ 'UI/UX Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'General UI',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires:
     [ 'Web and Mobile Developer',
       'Intern (App Developer)',
       'Operations Developer',
       'iOS Developer',
       'Software Developer',
       'Technology Evangelist' ],
    ios: 4,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Gerrit Technology International',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Principal' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Gesto',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Mobile Engineer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Getty Images',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires:
     [ 'IOS Developer',
       'Web Developer',
       'Mobile Software Engineer',
       'Web Developer' ],
    ios: 2,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 3 },
  { company: 'GobySavvy',
    state: 'CA',
    city: 'Long Beach',
    size: '10-100',
    hires: [ 'UX Designer and Front End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Google',
    state: 'WA',
    city: 'Bothell',
    size: '10,000+',
    hires: [ 'IT Support Specialist' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Grove Labs',
    state: 'MA',
    city: 'Boston',
    size: '<10',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Hash Interactive',
    state: 'ND',
    city: 'Fargo',
    size: '<10',
    hires: [ 'Lead Developer - Wordpress' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'HasOffers',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Front-End Developer', 'Software Support Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'HCL Technologies',
    state: 'WA',
    city: 'Redmond',
    size: '10,000+',
    hires: [ 'IOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'HealthSparq',
    state: 'OR',
    city: 'Portland',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Helpful Human',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Full-Stack Dev' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'HERE',
    state: 'Canada',
    city: 'Vancouver',
    size: '1,000-10,000',
    hires: [ 'Technical Writer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'HFA',
    state: 'unknown',
    city: 'unknown',
    size: '100-1,000',
    hires: [ 'RoR Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'High 5 Software',
    state: 'WA',
    city: 'Kenmore',
    size: '10-100',
    hires: [ 'Software Support Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Hire Up',
    state: 'CA',
    city: 'Fresno',
    size: '10-100',
    hires: [ 'Intern', 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 2,
    python: 0,
    ux: 0 },
  { company: 'Holland America Line',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires:
     [ 'Software Developer',
       'UX Designer, Front End Developer',
       'Web Developer/QA Lead',
       'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 1,
    rails: 2 },
  { company: 'IAS Claim Services',
    state: 'unknown',
    city: 'unknown',
    size: '10-100',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'iCentris',
    state: 'UT',
    city: 'Woods Cross',
    size: '10-100',
    hires: [ 'Ruby Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'ID.me',
    state: 'VA',
    city: 'McLean',
    size: '10-100',
    hires: [ 'junior software engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'IMS Health',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'InfoReliance Corporation',
    state: 'WA',
    city: 'Joint Base Lewis-McChord',
    size: '100-1,000',
    hires: [ 'Mobile Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Ingeniux Corporation',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Innovari',
    state: 'OR',
    city: 'Hillsboro',
    size: '10-100',
    hires: [ 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'INRIX',
    state: 'WA',
    city: 'Kirkland',
    size: '100-1,000',
    hires: [ 'Software Developer (iOS)' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Inside Social',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'JavaScript Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Intego',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'UX Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Integral GIS',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Interloc Solutions',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'iOS Software Development Engineer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Iron Horse Rails Consulting',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'iSoftStone',
    state: 'WA',
    city: 'Kirkland',
    size: '10,000+',
    hires:
     [ 'Software Developer Engineer',
       'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 2 },
  { company: 'JOLT Labs',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer', 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 2 },
  { company: 'Jordan Crown',
    state: 'WA',
    city: 'Everett',
    size: '<10',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Joy Life',
    state: 'unknown',
    city: 'unknown',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'K2',
    state: 'WA',
    city: 'Bellevue',
    size: '100-1,000',
    hires: [ 'Junior Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Kelley Blue Book',
    state: 'CA',
    city: 'Irvine',
    size: '100-1,000',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Korrio',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Kotis Design',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'L4 Mobile',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Software Engineer', 'Mobile Software Engineer' ],
    ios: 1,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Level 11',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Quality Assurance Engineer/SDET' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Leviathan Security Group',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'DevOps Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Lifespeed.io',
    state: 'CA',
    city: 'Irvine',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'LIFFFT',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Lilium Stargazer LLC',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Founder' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'LION Associates',
    state: 'CA',
    city: 'Berkeley',
    size: '<10',
    hires: [ 'Front-End Developer / UI Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'LiquidPlanner',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'LOUD Technologies, Inc.',
    state: 'WA',
    city: 'Woodinville',
    size: '100-1,000',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Lumidatum',
    state: 'WA',
    city: 'Bellevue',
    size: '<10',
    hires: [ 'Full-Stack Developer', 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 2,
    ux: 0 },
  { company: 'Luminous Creative',
    state: 'WA',
    city: 'Everett',
    size: '10-100',
    hires: [ 'UX Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Lumobee',
    state: 'WA',
    city: 'Redmond',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Magoosh',
    state: 'CA',
    city: 'Berkeley',
    size: '10-100',
    hires: [ 'Product Manager' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Makapen Co',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Founder' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Makepen Co',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Marchex',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Maxsam Partners',
    state: 'WA',
    city: 'Newcastle',
    size: '100-1,000',
    hires: [ 'Visual Designer/Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'MedBridge',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Developer', 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Microsoft Corporation',
    state: 'WA',
    city: 'Redmond',
    size: '10,000+',
    hires:
     [ 'Intern',
       'Intern',
       'Software Development Engineer',
       'Platform Engineer',
       'Visual Designer',
       'Marketing Automation Specialist',
       'Web Producer',
       'Design Developer',
       'Web Producer',
       'Software Development Engineer',
       'Software Developer',
       'Software Engineer II',
       'Data Analyst',
       'Engineering-Non-Product Development',
       'Front-End Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 8,
    python: 0,
    ux: 5,
    rails: 3 },
  { company: 'MiMedia',
    state: 'NY',
    city: 'Brooklyn',
    size: '10-100',
    hires: [ 'Front-end web developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Mobiquity',
    state: 'unknown',
    city: 'unknown',
    size: '10-100',
    hires: [ 'Mobile Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'ModeSens',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Moz',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'SDET' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Mozato',
    state: 'TX',
    city: 'Irving',
    size: '<10',
    hires: [ 'Sr. Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'MPI Computers',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'IT Subcontractor' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Myroya, LLC',
    state: 'WA',
    city: 'San Francisco',
    size: '<10',
    hires: [ 'RoR Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'National Center for Telehealth & Technology',
    state: 'WA',
    city: 'Joint Base Lewis-McChord',
    size: '100-1,000',
    hires: [ 'Web Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'National Oceanic and Atmospheric Administration',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Navman Wireless USA',
    state: 'CA',
    city: 'Pleasanton',
    size: '100-1,000',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'NBCUniversal',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires: [ 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Nike',
    state: 'OR',
    city: 'Beaverton',
    size: '10,000+',
    hires: [ 'Senior Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'NIKE, Inc.',
    state: 'OR',
    city: 'Beaverton',
    size: '100-1,000',
    hires: [ 'Software Developer', 'Front-End Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Nimia',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'NIRD',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Software Developer', 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 2 },
  { company: 'Nomic',
    state: 'CA',
    city: 'Oakland',
    size: '<10',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Nordstrom, Inc.',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires:
     [ 'Interactive Developer',
       'Python Developer',
       'Interactive Developer',
       'iOS Developer',
       'iOS Developer',
       'Interactive Developer',
       'iOS Developer',
       'Customer Mobile Developer' ],
    ios: 4,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 3 },
  { company: 'Novant Health',
    state: 'SC',
    city: 'Fort Mill',
    size: '10,000+',
    hires: [ 'Mobile Applications Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'OfferUp',
    state: 'WA',
    city: 'Bellevue',
    size: '10-100',
    hires:
     [ 'Software Developer',
       'Software Developer',
       'Software Developer (Python)' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 3,
    ux: 0 },
  { company: 'Only the Beat',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'CTO, Co-Founder' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Orthocare Innovations',
    state: 'WA',
    city: 'Mountlake Terrace',
    size: '10-100',
    hires: [ 'Senior Software Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Ozone International LLC',
    state: 'WA',
    city: 'Bainbridge Island',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Paladin Data Systems Corporation',
    state: 'WA',
    city: 'Poulsbo',
    size: '10-100',
    hires: [ 'Junior Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Palaemon',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Owner' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Patent Navigation, Inc.',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'coding and functionality design' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Pawzii',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Co-Founder', 'Founder', 'Ruby on Rails Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 3 },
  { company: 'Peach',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'PebbleBee',
    state: 'WA',
    city: 'Issaquah',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Pellego',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Phluant',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Full Stack Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Pixel Design',
    state: 'Ireland',
    city: 'Dublin',
    size: '1,000-10,000',
    hires: [ 'Web Designer and Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Placements.io',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Software Developer', 'Junior Rails dev' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 2 },
  { company: 'Pointmarc',
    state: 'WA',
    city: 'Bellevue',
    size: '10-100',
    hires: [ 'JavaScript Developer', 'Solution Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 1 },
  { company: 'Pokémon',
    state: 'WA',
    city: 'Bellevue',
    size: '100-1,000',
    hires: [ 'Python Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Pop Art, Inc.',
    state: 'OR',
    city: 'Portland',
    size: '10-100',
    hires: [ 'Software Developer (iOS)' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Porch',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Intern / Front end Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Powderhook',
    state: 'NE',
    city: 'Lincoln',
    size: '<10',
    hires: [ 'RoR Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Power Supply',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Apprentice UX Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Providence Health & Services',
    state: 'WA',
    city: 'Renton',
    size: '10,000+',
    hires: [ 'Quality Assurance Analyst' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Publicis Seattle',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Punchcut',
    state: 'CA',
    city: 'San Francisco',
    size: '10-100',
    hires: [ 'Senior Visual Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'QuickMedical',
    state: 'WA',
    city: 'Issaquah',
    size: '10-100',
    hires: [ 'Entry-Level Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Ravenna Solutions',
    state: 'WA',
    city: 'Bellevue',
    size: '10-100',
    hires:
     [ 'Software Design Engineer',
       'Customer Success Representative' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1,
    rails: 1 },
  { company: 'ReadyPulse',
    state: 'CA',
    city: 'San Carlos',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Rebls',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Lead, Product Development & Design' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Recurrence',
    state: 'WA',
    city: 'Bellevue',
    size: '<10',
    hires: [ 'Senior Full-Stack Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Redfin',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Reputation.com',
    state: 'CA',
    city: 'Redwood City',
    size: '100-1,000',
    hires: [ 'Web Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Rhapsody',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer', 'Mobile Software Engineer', 'Web Developer' ],
    ios: 2,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Rhino Camera Gear',
    state: 'WA',
    city: 'Puyallup',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Rick Steve\'s Europe',
    state: 'WA',
    city: 'Edmonds',
    size: '100-1,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Rover',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Salesforce Marketing Cloud',
    state: 'WA',
    city: 'Bellevue',
    size: '10,000+',
    hires: [ 'Senior Consultant, Solution Architect' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Saltbox',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Junior JavaScript Developer', 'Jr Developer Wordpress' ],
    ios: 1,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Samepage Health',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'ScrollMotion',
    state: 'CA',
    city: 'La Jolla',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'SeaMonster Studios',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Lead Web Developer', 'Lead Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Seattle Central College',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Instructor' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Seerflix Inc.',
    state: 'WA',
    city: 'Redmond',
    size: '<10',
    hires: [ 'Full-Stack Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Sensor Tower',
    state: 'CA',
    city: 'San Francisco',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Share2give',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Full-stack JavaScript Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Shiftboard',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'ShipHawk',
    state: 'CA',
    city: 'Santa Barbara',
    size: '10-100',
    hires: [ 'iOS Contractor' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Shippable',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires:
     [ 'Graphic Design/Marketing Intern',
       'Software Engineer',
       'Software Developer',
       'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 3,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Simplex Solutions',
    state: 'CA',
    city: 'Irvine',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Simply Measured',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Junior Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Siren',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'iOS Developer', 'Software Engineer', 'RoR Developer' ],
    ios: 2,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Sixth Ave Studios',
    state: 'WA',
    city: 'Tacoma',
    size: '10-100',
    hires: [ 'Front-End Web Developer', 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 2,
    python: 0,
    ux: 0 },
  { company: 'SkyKick',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'QA Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Slalom Consulting',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Consultant (Front-End Developer)', 'Consultant' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 1 },
  { company: 'Smartsheet',
    state: 'WA',
    city: 'Bellevue',
    size: '100-1,000',
    hires:
     [ 'UI Developer / Front End Developer',
       'Senior Mobile Software Development Engineer',
       'Front-End UI Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 2 },
  { company: 'SmartSource Management',
    state: 'CO',
    city: 'Denver',
    size: '10-100',
    hires: [ 'JavaScript Engineer', 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 2,
    python: 0,
    ux: 0 },
  { company: 'Smilebox',
    state: 'WA',
    city: 'Redmond',
    size: '10-100',
    hires: [ 'Senior Front End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Snap!',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Web Developer', 'Software Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Socrata',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires:
     [ 'Front-End Developer',
       'Front-End Developer',
       'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 3 },
  { company: 'Sonata Software',
    state: 'WA',
    city: 'Redmond',
    size: '1,000-10,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'SPARC',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Sporcle',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Stella & Dot',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires:
     [ 'Software Engineer',
       'Web Content Developer',
       'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 2,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'STRATUS Solutions, Inc.',
    state: 'MD',
    city: 'Ellicott City',
    size: '10-100',
    hires: [ 'Senior Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Sublime Media',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'SubmitNet',
    state: 'OR',
    city: 'Portland',
    size: '10-100',
    hires: [ 'Python Programmer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Substantial',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires:
     [ 'Software Developer',
       'Web Application Engineer',
       'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 3 },
  { company: 'Support.com, Inc.',
    state: 'CA',
    city: 'Redwood City',
    size: '1,000-10,000',
    hires: [ 'Computer Support Tech' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Switch Inc.',
    state: 'Canada',
    city: 'Edmonton, Alberta',
    size: '<10',
    hires: [ 'Front-End Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Synch',
    state: 'CA',
    city: 'San Francisco',
    size: '10-100',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'T-Mobile',
    state: 'WA',
    city: 'Bellevue',
    size: '10,000+',
    hires: [ 'RoR Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Tag Creative Studio',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Tagtoo',
    state: 'Taiwan',
    city: 'Taipei',
    size: '10-100',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'The Boeing Company',
    state: 'WA',
    city: 'Kent',
    size: '10,000+',
    hires: [ 'Software Engineer I', 'Mobile Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'The Institute for Health Metrics and Evaluation',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'JavaScript Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'The Raytheon Company',
    state: 'unknown',
    city: 'unknown',
    size: '10,000+',
    hires: [ 'Computer Programmer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'The Seattle Women\'s Jazz Orchestra',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Executive Director' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'The University of Washington',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires: [ 'Web Application Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'The Walt Disney Company',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Software Engineer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Time Inc.',
    state: 'WA',
    city: 'Seattle',
    size: '10,000+',
    hires: [ 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Trade Tech, Inc.',
    state: 'WA',
    city: 'Issaquah',
    size: '10-100',
    hires: [ 'Backend Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'TreeHouse Interactive',
    state: 'NY',
    city: 'New York',
    size: '10-100',
    hires: [ 'Junior Interactive Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Trueblue',
    state: 'WA',
    city: 'Tacoma',
    size: '10-100',
    hires: [ 'Tools Integration Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'TUNE',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires:
     [ 'Software Support Engineer',
       'Software Support Engineer',
       'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 3,
    python: 0,
    ux: 0 },
  { company: 'Udemy',
    state: 'CA',
    city: 'San Francisco',
    size: '10-100',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Unity Technologies',
    state: 'WA',
    city: 'Bellevue',
    size: '100-1,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'UP Global',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'UX Designer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'USEED',
    state: 'MT',
    city: 'Bozeman',
    size: '<10',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Vaisala',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'Vectorform',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Interactive Engineer', 'Interactive Solutions Engineer' ],
    ios: 2,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Vehicle',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Junior Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Verizon Wireless',
    state: 'unknown',
    city: 'unknown',
    size: '10,000+',
    hires: [ 'JavaScript Contractor', 'Ruby Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Vertafore',
    state: 'WA',
    city: 'Bothell',
    size: '1,000-10,000',
    hires: [ 'Software Engineer', 'Product Manager' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1,
    rails: 1 },
  { company: 'Wargaming Seattle',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Associate Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Wayfair',
    state: 'MA',
    city: 'Boston',
    size: '<10',
    hires: [ 'Software Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Wealthfile',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Weple',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Western Union Digital Ventures',
    state: 'CA',
    city: 'San Francisco',
    size: '1,000-10,000',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Wetpaint',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'Dev Ops Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 1,
    ux: 0 },
  { company: 'What.It.Is',
    state: 'TX',
    city: 'Austin',
    size: '<10',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 },
  { company: 'Whitepages',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Sales Executive' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Windermere Real Estate',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'WorkZeit',
    state: 'WA',
    city: 'Seattle',
    size: '<10',
    hires: [ 'Web Developer', 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 2 },
  { company: 'Xbox',
    state: 'WA',
    city: 'Redmond',
    size: '10,000+',
    hires: [ 'Web Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Xome',
    state: 'TX',
    city: 'Lewisville',
    size: '1,000-10,000',
    hires: [ 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'Yapta',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Software Engineer', 'Software Development Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 1,
    ux: 0 },
  { company: 'zCrowd',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Engineer' ],
    ios: 0,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0 },
  { company: 'ZIIBRA',
    state: 'WA',
    city: 'Seattle',
    size: '10-100',
    hires: [ 'Front-End Developer', 'Software Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 2 },
  { company: 'Zillow Group',
    state: 'WA',
    city: 'Seattle',
    size: '1,000-10,000',
    hires:
     [ 'Software Development Engineer',
       'Software Development Engineer',
       'Front-end Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 1,
    python: 0,
    ux: 0,
    rails: 1 },
  { company: 'Zomato',
    state: 'WA',
    city: 'Seattle',
    size: '100-1,000',
    hires: [ 'iOS Developer' ],
    ios: 1,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 0 },
  { company: 'Zumiez',
    state: 'WA',
    city: 'Lynwood',
    size: '1,000-10,000',
    hires: [ 'Front-End Developer' ],
    ios: 0,
    ruby: 0,
    javascript: 0,
    python: 0,
    ux: 1 } ];
